import { Order } from "@/types/entities";

export const mockOrders: any[] = [
  {
    id: 9193,
    orderNo: "#5499",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 120.0,
    status: "cancelled",
    createdAt: "2026-01-29T08:12:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "RESTAURANT_REJECTED",
  },
  {
    id: 9192,
    orderNo: "#4712",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 120,
    status: "cancelled",
    createdAt: "2026-01-17T14:38:00Z",
    createdBy: "Kot Kot",
    deliveryStatus: "RESTAURANT_REJECTED",
  },
  {
    id: 9191,
    orderNo: "#8954",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 450,
    status: "pending",
    createdAt: "2026-01-17T14:35:00Z",
    createdBy: "Kot Kot",
    deliveryStatus: "PENDING",
  },
  {
    id: 9190,
    orderNo: "#9465",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 72.0,
    status: "accepted",
    createdAt: "2026-01-17T08:59:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "CONFIRMED",
  },
  {
    id: 9189,
    orderNo: "#6667",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 24.0,
    status: "accepted",
    createdAt: "2026-01-17T07:45:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "CONFIRMED",
  },
  {
    id: 9188,
    orderNo: "#3896",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 24.0,
    status: "delivered",
    createdAt: "2026-01-17T07:45:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "DELIVERED",
  },
  {
    id: 9187,
    orderNo: "#8329",
    restaurantName: "Mus diner",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 610,
    status: "preparing",
    createdAt: "2025-12-28T11:14:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "PREPARING",
  },
  {
    id: 9186,
    orderNo: "#5512",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 340,
    status: "ready",
    createdAt: "2026-01-16T12:45:00Z",
    createdBy: "Kot Kot",
    deliveryStatus: "READY_FOR_PICKUP",
  },
  {
    id: 9185,
    orderNo: "#9234",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 198,
    status: "out_for_delivery",
    createdAt: "2026-01-16T11:30:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "PICKED_UP",
  },
  {
    id: 9184,
    orderNo: "#4156",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 425,
    status: "out_for_delivery",
    createdAt: "2026-01-16T09:15:00Z",
    createdBy: "Kot Kot",
    deliveryStatus: "ON_THE_WAY",
  },
  {
    id: 9183,
    orderNo: "#6789",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    status: "delivered",
    createdAt: "2026-01-15T20:05:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "DELIVERED",
  },
  {
    id: 9182,
    orderNo: "#6789",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    status: "delivered",
    createdAt: "2026-01-15T20:05:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "DELIVERED",
  },
  {
    id: 9181,
    orderNo: "#6789",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    status: "cancelled",
    createdAt: "2026-01-15T20:05:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "DRIVER_REJECTED",
  },
  {
    id: 9180,
    orderNo: "#6789",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    status: "cancelled",
    createdAt: "2026-01-15T20:05:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "DRIVER_REJECTED",
  },
  {
    id: 9179,
    orderNo: "#6789",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    status: "cancelled",
    createdAt: "2026-01-15T20:05:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "DRIVER_REJECTED",
  },
  {
    id: 9178,
    orderNo: "#6789",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    status: "cancelled",
    createdAt: "2026-01-15T20:05:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "DRIVER_REJECTED",
  },
  {
    id: 9177,
    orderNo: "#6789",
    restaurantName: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    status: "cancelled",
    createdAt: "2026-01-15T20:05:00Z",
    createdBy: "Bele Shewa",
    deliveryStatus: "RESTAURANT_REJECTED",
  },
];
