import { Order } from "@/types/entities";

export const mockOrders: Order[] = [
  {
    id: 9193,
    orderNo: "#5499",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 120.0,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "29-Jan-2026 08:12",
    createdBy: "Bele Shewa",
  },
  {
    id: 9192,
    orderNo: "#4712",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 120,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "17-Jan-2026 14:38",
    createdBy: "Kot Kot",
  },
  {
    id: 9191,
    orderNo: "#8954",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 450,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "17-Jan-2026 14:35",
    createdBy: "Kot Kot",
  },
  {
    id: 9190,
    orderNo: "#9465",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 72.0,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "17-Jan-2026 08:59",
    createdBy: "Bele Shewa",
  },
  {
    id: 9189,
    orderNo: "#6667",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 24.0,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "17-Jan-2026 07:45",
    createdBy: "Bele Shewa",
  },
  {
    id: 9188,
    orderNo: "#3896",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 24.0,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "17-Jan-2026 07:45",
    createdBy: "Bele Shewa",
  },
  {
    id: 9187,
    orderNo: "#8329",
    store: "Mus diner",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 610,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "28-Dec-2025 11:14",
    createdBy: "Bele Shewa",
  },
];
