import { Order } from "@/types/entities";

export const mockOrders: Order[] = [
  {
    id: 9193,
    orderNo: "#5499",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 120.0,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "29-Jan-2026 08:12",
    createdBy: "Bele Shewa",
  },
  {
    id: 9192,
    orderNo: "#4712",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 120,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "17-Jan-2026 14:38",
    createdBy: "Kot Kot",
  },
  {
    id: 9191,
    orderNo: "#8954",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 450,
    deliveryStatus: "PENDING",
    createdOn: "17-Jan-2026 14:35",
    createdBy: "Kot Kot",
  },
  {
    id: 9190,
    orderNo: "#9465",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 72.0,
    deliveryStatus: "CONFIRMED",
    createdOn: "17-Jan-2026 08:59",
    createdBy: "Bele Shewa",
  },
  {
    id: 9189,
    orderNo: "#6667",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 24.0,
    deliveryStatus: "CONFIRMED",
    createdOn: "17-Jan-2026 07:45",
    createdBy: "Bele Shewa",
  },
  {
    id: 9188,
    orderNo: "#3896",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 24.0,
    deliveryStatus: "DELIVERED",
    createdOn: "17-Jan-2026 07:45",
    createdBy: "Bele Shewa",
  },
  {
    id: 9187,
    orderNo: "#8329",
    store: "Mus diner",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 610,
    deliveryStatus: "PREPARING",
    createdOn: "28-Dec-2025 11:14",
    createdBy: "Bele Shewa",
  },
  {
    id: 9186,
    orderNo: "#5512",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 340,
    deliveryStatus: "READY_FOR_PICKUP",
    createdOn: "16-Jan-2026 12:45",
    createdBy: "Kot Kot",
  },
  {
    id: 9185,
    orderNo: "#9234",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 198,
    deliveryStatus: "PICKED_UP",
    createdOn: "16-Jan-2026 11:30",
    createdBy: "Bele Shewa",
  },
  {
    id: 9184,
    orderNo: "#4156",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 425,
    deliveryStatus: "ON_THE_WAY",
    createdOn: "16-Jan-2026 09:15",
    createdBy: "Kot Kot",
  },
  {
    id: 9183,
    orderNo: "#6789",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    deliveryStatus: "DELIVERED",
    createdOn: "15-Jan-2026 20:05",
    createdBy: "Bele Shewa",
  },
  {
    id: 9182,
    orderNo: "#6789",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    deliveryStatus: "DELIVERED",
    createdOn: "15-Jan-2026 20:05",
    createdBy: "Bele Shewa",
  },
  {
    id: 9181,
    orderNo: "#6789",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    deliveryStatus: "DRIVER_REJECTED",
    createdOn: "15-Jan-2026 20:05",
    createdBy: "Bele Shewa",
  },
  {
    id: 9180,
    orderNo: "#6789",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    deliveryStatus: "DRIVER_REJECTED",
    createdOn: "15-Jan-2026 20:05",
    createdBy: "Bele Shewa",
  },
  {
    id: 9179,
    orderNo: "#6789",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    deliveryStatus: "DRIVER_REJECTED",
    createdOn: "15-Jan-2026 20:05",
    createdBy: "Bele Shewa",
  },
  {
    id: 9178,
    orderNo: "#6789",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    deliveryStatus: "DRIVER_REJECTED",
    createdOn: "15-Jan-2026 20:05",
    createdBy: "Bele Shewa",
  },
  {
    id: 9177,
    orderNo: "#6789",
    store: "Habibi’s Kitchen",
    address: "XQMQ+9G8, Addis Ababa, Addis Ababa, Ethiopia",
    totalPrice: 89,
    deliveryStatus: "RESTAURANT_REJECTED",
    createdOn: "15-Jan-2026 20:05",
    createdBy: "Bele Shewa",
  },
];
