"use client";

import { useState } from "react";
import type { ChatUser, ChatMessage } from "@/types/entities";
import { UsersList } from "./UsersList";
import { ChatWindow } from "./ChatWindow";

// Mock data
const mockUsers: ChatUser[] = [
  {
    id: 1,
    name: "Hassen Mohammed",
    status: "online",
    lastMessage: "You too! 👋",
    lastMessageTime: "8:13 AM",
    unreadCount: 0,
  },
  {
    id: 2,
    name: "John Doe",
    status: "online",
    lastMessage: "It's blocking the order flow on mobile.",
    lastMessageTime: "10:11 AM",
    unreadCount: 2,
  },
  {
    id: 3,
    name: "Jane Smith",
    status: "offline",
    lastMessage: "Happy to help! I'll send you my notes.",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
  },
  {
    id: 4,
    name: "Michael Brown",
    status: "online",
    lastMessage: "Also, the client confirmed they're happy 🎉",
    lastMessageTime: "11:12 AM",
    unreadCount: 1,
  },
  {
    id: 5,
    name: "Sarah Wilson",
    status: "away",
    lastMessage: "That would be super helpful. Got it 😊",
    lastMessageTime: "9:12 AM",
    unreadCount: 0,
  },
  {
    id: 6,
    name: "David Lee",
    status: "online",
    lastMessage: "Thanks a lot, really appreciate it!",
    lastMessageTime: "4:52 PM",
    unreadCount: 3,
  },
  {
    id: 7,
    name: "Emily Davis",
    status: "offline",
    lastMessage: "Yes, definitely. Let's do it! 🙌",
    lastMessageTime: "2 days ago",
    unreadCount: 0,
  },
  {
    id: 8,
    name: "Robert Johnson",
    status: "online",
    lastMessage: "I'll check and get back to you.",
    lastMessageTime: "2:00 PM",
    unreadCount: 0,
  },
  {
    id: 9,
    name: "Lisa Anderson",
    status: "away",
    lastMessage: "Sounds good! Let me know what they say.",
    lastMessageTime: "10:45 AM",
    unreadCount: 0,
  },
  {
    id: 10,
    name: "James Martinez",
    status: "offline",
    lastMessage: "I'll ping you once the order flow is ready.",
    lastMessageTime: "3 days ago",
    unreadCount: 0,
  },
];

const mockMessages: ChatMessage[] = [
  // ── Hassen Mohammed (id: 1) — 5-day conversation history ─
  // Day 1: Feb 14
  {
    id: 101,
    senderId: 100,
    receiverId: 1,
    content:
      "Morning Hassen! Quick heads-up — the client meeting is moved to Thursday.",
    timestamp: "2026-02-14T08:05:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 102,
    senderId: 1,
    receiverId: 100,
    content: "Got it, thanks for letting me know. I'll update my calendar.",
    timestamp: "2026-02-14T08:10:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 103,
    senderId: 100,
    receiverId: 1,
    content: "Also, can you prepare a short summary of last week's progress?",
    timestamp: "2026-02-14T08:12:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 104,
    senderId: 1,
    receiverId: 100,
    content: "Sure, I'll have it ready by noon.",
    timestamp: "2026-02-14T08:14:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 105,
    senderId: 1,
    receiverId: 100,
    content:
      "Done! Just sent it to your email. Let me know if you need anything added.",
    timestamp: "2026-02-14T12:03:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 106,
    senderId: 100,
    receiverId: 1,
    content: "Perfect, exactly what I needed. Great work! 👍",
    timestamp: "2026-02-14T12:20:00Z",
    isRead: true,
    isSent: true,
  },

  // Day 2: Feb 15
  {
    id: 107,
    senderId: 1,
    receiverId: 100,
    content:
      "Hey, I ran into a weird issue with the auth flow. Users are getting logged out randomly.",
    timestamp: "2026-02-15T09:30:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 108,
    senderId: 100,
    receiverId: 1,
    content: "That's strange. Is it happening on all devices or just mobile?",
    timestamp: "2026-02-15T09:35:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 109,
    senderId: 1,
    receiverId: 100,
    content:
      "Seems like mostly mobile. I think it might be the token refresh logic.",
    timestamp: "2026-02-15T09:38:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 110,
    senderId: 100,
    receiverId: 1,
    content:
      "Check the refresh token expiry. I think we set it to 1 hour by mistake.",
    timestamp: "2026-02-15T09:42:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 111,
    senderId: 1,
    receiverId: 100,
    content: "You're right! It was 1 hour. Changed it to 7 days. Testing now.",
    timestamp: "2026-02-15T10:05:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 112,
    senderId: 100,
    receiverId: 1,
    content: "Nice catch! Let me know how the tests go.",
    timestamp: "2026-02-15T10:07:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 113,
    senderId: 1,
    receiverId: 100,
    content: "All good now. Deployed the fix. 🎉",
    timestamp: "2026-02-15T11:30:00Z",
    isRead: true,
    isSent: true,
  },

  // Day 3: Feb 16
  {
    id: 114,
    senderId: 1,
    receiverId: 100,
    content: "Morning! The client loved the new onboarding screens.",
    timestamp: "2026-02-16T08:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 115,
    senderId: 100,
    receiverId: 1,
    content: "That's great to hear! Did they have any feedback?",
    timestamp: "2026-02-16T08:05:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 116,
    senderId: 1,
    receiverId: 100,
    content:
      "They want the progress bar to be more visible. Maybe make it thicker?",
    timestamp: "2026-02-16T08:08:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 117,
    senderId: 100,
    receiverId: 1,
    content: "Good point. I'll bump it from 4px to 8px and send you a preview.",
    timestamp: "2026-02-16T08:12:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 118,
    senderId: 1,
    receiverId: 100,
    content:
      "Sounds good! Also, they asked if we can add a 'Skip' button on step 2.",
    timestamp: "2026-02-16T08:15:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 119,
    senderId: 100,
    receiverId: 1,
    content: "Easy enough. I'll add it to today's tasks.",
    timestamp: "2026-02-16T08:17:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 120,
    senderId: 1,
    receiverId: 100,
    content: "Awesome, thanks! Have a great day 😊",
    timestamp: "2026-02-16T08:20:00Z",
    isRead: true,
    isSent: true,
  },

  // Day 4: Feb 17
  {
    id: 121,
    senderId: 100,
    receiverId: 1,
    content: "Hassen, did you get a chance to review the new dashboard design?",
    timestamp: "2026-02-17T10:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 122,
    senderId: 1,
    receiverId: 100,
    content:
      "Yes! I really like the layout. The sidebar feels much cleaner now.",
    timestamp: "2026-02-17T10:05:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 123,
    senderId: 100,
    receiverId: 1,
    content: "Glad you like it! Any sections you'd change?",
    timestamp: "2026-02-17T10:07:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 124,
    senderId: 1,
    receiverId: 100,
    content:
      "The analytics cards could use a bit more spacing. Otherwise it's solid.",
    timestamp: "2026-02-17T10:10:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 125,
    senderId: 100,
    receiverId: 1,
    content: "Noted! I'll adjust the padding. Thanks for the feedback.",
    timestamp: "2026-02-17T10:13:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 126,
    senderId: 1,
    receiverId: 100,
    content: "No problem. Looking forward to the final version!",
    timestamp: "2026-02-17T10:15:00Z",
    isRead: true,
    isSent: true,
  },

  // Day 5: Feb 18 (today)
  {
    id: 1,
    senderId: 1,
    receiverId: 100,
    content: "Hey! How's everything going on your end?",
    timestamp: "2026-02-18T08:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 2,
    senderId: 100,
    receiverId: 1,
    content: "Pretty good, just wrapping up the sprint. You?",
    timestamp: "2026-02-18T08:02:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 3,
    senderId: 1,
    receiverId: 100,
    content: "Same here. Did you push the final dashboard version?",
    timestamp: "2026-02-18T08:04:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 4,
    senderId: 100,
    receiverId: 1,
    content: "Yes! Just pushed it. The spacing is fixed and it looks great.",
    timestamp: "2026-02-18T08:06:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 5,
    senderId: 1,
    receiverId: 100,
    content: "Awesome! I'll review it and share with the team.",
    timestamp: "2026-02-18T08:08:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 6,
    senderId: 100,
    receiverId: 1,
    content: "Perfect, I'll review it first thing tomorrow morning.",
    timestamp: "2026-02-18T08:10:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 7,
    senderId: 1,
    receiverId: 100,
    content: "Sounds good. Have a great evening!",
    timestamp: "2026-02-18T08:12:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 8,
    senderId: 100,
    receiverId: 1,
    content: "You too! 👋",
    timestamp: "2026-02-18T08:13:00Z",
    isRead: false,
    isSent: true,
  },

  // ── John Doe (id: 2) ─────────────────────────────────────
  {
    id: 9,
    senderId: 100,
    receiverId: 2,
    content: "Hey John, are you free for a quick call this afternoon?",
    timestamp: "2026-02-18T10:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 10,
    senderId: 2,
    receiverId: 100,
    content: "Sure! What time works for you?",
    timestamp: "2026-02-18T10:05:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 11,
    senderId: 100,
    receiverId: 2,
    content: "Around 3 PM? We need to go over the API integration.",
    timestamp: "2026-02-18T10:07:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 12,
    senderId: 2,
    receiverId: 100,
    content: "3 PM works. I'll send you the meeting link.",
    timestamp: "2026-02-18T10:09:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 13,
    senderId: 2,
    receiverId: 100,
    content: "Also, did you check the bug I reported yesterday?",
    timestamp: "2026-02-18T10:10:00Z",
    isRead: false,
    isSent: true,
  },
  {
    id: 14,
    senderId: 2,
    receiverId: 100,
    content: "It's blocking the order flow on mobile.",
    timestamp: "2026-02-18T10:11:00Z",
    isRead: false,
    isSent: true,
  },

  // ── Jane Smith (id: 3) ───────────────────────────────────
  {
    id: 15,
    senderId: 3,
    receiverId: 100,
    content:
      "Hi! I just submitted the Q1 report. Can you take a look when you get a chance?",
    timestamp: "2026-02-17T09:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 16,
    senderId: 100,
    receiverId: 3,
    content: "Of course! I'll review it this afternoon.",
    timestamp: "2026-02-17T09:15:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 17,
    senderId: 3,
    receiverId: 100,
    content:
      "Thanks! There are a few charts on page 4 I'm not 100% sure about.",
    timestamp: "2026-02-17T09:17:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 18,
    senderId: 100,
    receiverId: 3,
    content: "I'll pay extra attention to those. Don't worry.",
    timestamp: "2026-02-17T09:20:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 19,
    senderId: 3,
    receiverId: 100,
    content: "You're the best, thank you so much! 🙏",
    timestamp: "2026-02-17T09:22:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 20,
    senderId: 100,
    receiverId: 3,
    content: "Happy to help! I'll send you my notes by 5 PM.",
    timestamp: "2026-02-17T09:25:00Z",
    isRead: true,
    isSent: true,
  },

  // ── Michael Brown (id: 4) ────────────────────────────────
  {
    id: 21,
    senderId: 100,
    receiverId: 4,
    content: "Michael, did the deployment go through?",
    timestamp: "2026-02-18T11:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 22,
    senderId: 4,
    receiverId: 100,
    content: "Yes! It went live about 20 minutes ago. No issues so far.",
    timestamp: "2026-02-18T11:05:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 23,
    senderId: 100,
    receiverId: 4,
    content: "Great! I'll monitor the error logs for the next hour.",
    timestamp: "2026-02-18T11:07:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 24,
    senderId: 4,
    receiverId: 100,
    content: "Good idea. I'll be around if anything comes up.",
    timestamp: "2026-02-18T11:09:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 25,
    senderId: 4,
    receiverId: 100,
    content:
      "Also, the client confirmed they're happy with the new features 🎉",
    timestamp: "2026-02-18T11:12:00Z",
    isRead: false,
    isSent: true,
  },

  // ── Sarah Wilson (id: 5) ─────────────────────────────────
  {
    id: 26,
    senderId: 5,
    receiverId: 100,
    content: "Hey, can you help me understand the new onboarding flow?",
    timestamp: "2026-02-18T09:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 27,
    senderId: 100,
    receiverId: 5,
    content: "Sure! Which part is confusing you?",
    timestamp: "2026-02-18T09:05:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 28,
    senderId: 5,
    receiverId: 100,
    content:
      "The step where users upload their documents. It's not clear what formats are accepted.",
    timestamp: "2026-02-18T09:07:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 29,
    senderId: 100,
    receiverId: 5,
    content:
      "Ah, we accept PDF, JPG, and PNG. I'll update the tooltip text to make it clearer.",
    timestamp: "2026-02-18T09:10:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 30,
    senderId: 5,
    receiverId: 100,
    content: "That would be super helpful. Got it, thanks! 😊",
    timestamp: "2026-02-18T09:12:00Z",
    isRead: true,
    isSent: true,
  },

  // ── David Lee (id: 6) ────────────────────────────────────
  {
    id: 31,
    senderId: 6,
    receiverId: 100,
    content: "Hey, I need the latest export of the user analytics.",
    timestamp: "2026-02-18T16:40:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 32,
    senderId: 100,
    receiverId: 6,
    content: "Sure, give me a few minutes to pull it together.",
    timestamp: "2026-02-18T16:42:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 33,
    senderId: 6,
    receiverId: 100,
    content: "No rush, I need it for the 5 PM meeting.",
    timestamp: "2026-02-18T16:43:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 34,
    senderId: 100,
    receiverId: 6,
    content: "I'll have it ready by 4:30. Should I send it to your email?",
    timestamp: "2026-02-18T16:45:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 35,
    senderId: 6,
    receiverId: 100,
    content: "Yes please! And can you also include the retention rate?",
    timestamp: "2026-02-18T16:50:00Z",
    isRead: false,
    isSent: true,
  },
  {
    id: 36,
    senderId: 6,
    receiverId: 100,
    content: "The team specifically asked for that metric.",
    timestamp: "2026-02-18T16:51:00Z",
    isRead: false,
    isSent: true,
  },
  {
    id: 37,
    senderId: 6,
    receiverId: 100,
    content: "Thanks a lot, really appreciate it!",
    timestamp: "2026-02-18T16:52:00Z",
    isRead: false,
    isSent: true,
  },

  // ── Emily Davis (id: 7) ──────────────────────────────────
  {
    id: 38,
    senderId: 100,
    receiverId: 7,
    content: "Emily, are you available for the design review on Thursday?",
    timestamp: "2026-02-16T13:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 39,
    senderId: 7,
    receiverId: 100,
    content: "Thursday works! Morning or afternoon?",
    timestamp: "2026-02-16T13:10:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 40,
    senderId: 100,
    receiverId: 7,
    content: "Let's do 10 AM. I'll book the conference room.",
    timestamp: "2026-02-16T13:12:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 41,
    senderId: 7,
    receiverId: 100,
    content: "Perfect! I'll prepare the mockups beforehand.",
    timestamp: "2026-02-16T13:15:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 42,
    senderId: 100,
    receiverId: 7,
    content: "Great. Should we invite the product team too?",
    timestamp: "2026-02-16T13:17:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 43,
    senderId: 7,
    receiverId: 100,
    content: "Yes, definitely. The more feedback the better. Let's do it! 🙌",
    timestamp: "2026-02-16T13:20:00Z",
    isRead: true,
    isSent: true,
  },

  // ── Robert Johnson (id: 8) ───────────────────────────────
  {
    id: 44,
    senderId: 100,
    receiverId: 8,
    content: "Robert, any update on the server migration?",
    timestamp: "2026-02-18T13:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 45,
    senderId: 8,
    receiverId: 100,
    content: "We're about 70% done. Should finish by tomorrow morning.",
    timestamp: "2026-02-18T13:10:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 46,
    senderId: 100,
    receiverId: 8,
    content: "Any downtime expected?",
    timestamp: "2026-02-18T13:12:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 47,
    senderId: 8,
    receiverId: 100,
    content: "We're planning a 15-minute window at 2 AM. Minimal impact.",
    timestamp: "2026-02-18T13:15:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 48,
    senderId: 100,
    receiverId: 8,
    content: "Sounds good. I'll notify the team.",
    timestamp: "2026-02-18T13:17:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 49,
    senderId: 8,
    receiverId: 100,
    content: "I'll check and get back to you if anything changes.",
    timestamp: "2026-02-18T14:00:00Z",
    isRead: true,
    isSent: true,
  },

  // ── Lisa Anderson (id: 9) ────────────────────────────────
  {
    id: 50,
    senderId: 100,
    receiverId: 9,
    content: "Lisa, I sent over the new pricing proposal. Did you get it?",
    timestamp: "2026-02-18T10:30:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 51,
    senderId: 9,
    receiverId: 100,
    content: "Yes, just opened it. Looks solid overall.",
    timestamp: "2026-02-18T10:35:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 52,
    senderId: 100,
    receiverId: 9,
    content: "Any concerns with the enterprise tier?",
    timestamp: "2026-02-18T10:37:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 53,
    senderId: 9,
    receiverId: 100,
    content: "The price point seems a bit high. Can we offer a 3-month trial?",
    timestamp: "2026-02-18T10:40:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 54,
    senderId: 100,
    receiverId: 9,
    content:
      "That's a good idea. I'll bring it up in the next leadership meeting.",
    timestamp: "2026-02-18T10:42:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 55,
    senderId: 9,
    receiverId: 100,
    content: "Sounds good! Let me know what they say.",
    timestamp: "2026-02-18T10:45:00Z",
    isRead: true,
    isSent: true,
  },

  // ── James Martinez (id: 10) ──────────────────────────────
  {
    id: 56,
    senderId: 100,
    receiverId: 10,
    content:
      "James, the client is asking for a progress update on the mobile app.",
    timestamp: "2026-02-15T08:00:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 57,
    senderId: 10,
    receiverId: 100,
    content: "We're on track. Authentication and home screen are done.",
    timestamp: "2026-02-15T08:10:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 58,
    senderId: 100,
    receiverId: 10,
    content: "What's left for the MVP?",
    timestamp: "2026-02-15T08:12:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 59,
    senderId: 10,
    receiverId: 100,
    content:
      "Order flow, notifications, and the profile screen. About 2 more weeks.",
    timestamp: "2026-02-15T08:15:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 60,
    senderId: 100,
    receiverId: 10,
    content:
      "Perfect. I'll relay that to the client. They'll be happy to hear it.",
    timestamp: "2026-02-15T08:17:00Z",
    isRead: true,
    isSent: true,
  },
  {
    id: 61,
    senderId: 10,
    receiverId: 100,
    content: "Thanks! I'll ping you once the order flow is ready for testing.",
    timestamp: "2026-02-15T09:05:00Z",
    isRead: true,
    isSent: true,
  },
];

const CURRENT_USER_ID = 100;

export function ChatInterface() {
  const [selectedUserId, setSelectedUserId] = useState<number | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>(mockMessages);

  const selectedUser = mockUsers.find((u) => u.id === selectedUserId) || null;
  const userMessages = messages.filter(
    (m) =>
      (m.senderId === selectedUserId && m.receiverId === CURRENT_USER_ID) ||
      (m.senderId === CURRENT_USER_ID && m.receiverId === selectedUserId),
  );

  const handleSendMessage = (content: string) => {
    const newMessage: ChatMessage = {
      id: messages.length + 1,
      senderId: CURRENT_USER_ID,
      receiverId: selectedUserId!,
      content,
      timestamp: new Date().toISOString(),
      isRead: false,
      isSent: true,
    };
    setMessages([...messages, newMessage]);
  };

  return (
    <div className="flex h-[calc(100vh-120px)] bg-white dark:bg-gray-900 rounded-lg overflow-hidden border">
      <UsersList
        users={mockUsers}
        selectedUserId={selectedUserId}
        onSelectUser={setSelectedUserId}
      />
      <ChatWindow
        selectedUser={selectedUser}
        messages={userMessages}
        currentUserId={CURRENT_USER_ID}
        onSendMessage={handleSendMessage}
      />
    </div>
  );
}
